import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import PopUp from "./_components/PopUp";
import NavBar from "./_components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figTree",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${figtree.variable} h-full antialiased relative overflow-hidden`}
    >
      <head>
          <script dangerouslySetInnerHTML={{__html: `
          if (localStorage.getItem('darkTheme') === 'true') {
            document.documentElement.classList.add('dark')
          }
        `}} />
      </head>
      
      <body className="h-full flex flex-col relative items-center overflow-hidden">
        <div className="flex flex-col h-full w-full  overflow-hidden " >
          <NavBar/>
          {children}
        </div>
        <PopUp />
      </body>

    </html>
  );
}
